const tipsArray = [
    "Try checking what magic items you have in your inventory.",
    "Have you checked what magic items you own recently?",
    "Sometimes it's okay to kill things, I promise.",
    "The Golden Vault was invented by John Goldenvault in the year 1323.",
    "You guys definitely forgot that you have a Mystery Key, didn't you.",
    "To push a target, it must be within your reach and no more than one size larger than you.",
    "Lawful Good doesn't mean Lawful Nice and Chaotic Neutral doesn't mean Chaotic Stupid.",
    "A creature that is Prone has disadvantage on all of its attack rolls until it stands up.",
    "Melee attacks against a creature that is Prone have advantage.",
    "Ranged attacks against a creature that is Prone have disadvantage.",
    "You can pause the game in D&D by standing up and walking away from the table.",
    "Meera Raheer's parents were city clerks, until the mayor framed them for embezzlement.",
    "You can save your progress in D&D by taking notes.",
    "Even if you can't see a creature, you can still attack it with disadvantage.",
    "If you are grappling a creature, you can move it with you at half your speed.",
    "Take notes. Take notes. Take notes. Take notes. Take notes. Take notes. Take notes. Take notes. Take notes. Take notes. Take notes.",
    "When damage reduces you to 0 hit points, you die immediately if the extra damage exceeds your hit point maximum.",
    "When you reduce a creature to 0 hit points with a melee attack, you can knock it out instead of killing it.",
    "You have advantage on attacks against creatures that cannot see you.",
    "The Varkenbluff History Museum houses the world's most complete restoration of a Plesiosaurus skeleton.",
    "You can stabilize a dying creature with a DC10 Medicine check or with a Healer's Kit.",
    "Any weapon with the Light property can be used in Two-Weapon Fighting.",
    "You can start a new save in D&D by striking your DM on the head with something heavy.",
    "You can make a High Jump of 3 + your Strength modifier by taking a 10 foot running start.",
    "You can Push, Carry, or Drag up to your Carrying Capacity (15 x your Strength score). You can double this amount but your speed becomes 5ft.",
    "Seriously, what was up with Alda Arkin - the museum curator - and her huge creepy doll?",
    "Dr. Cassee Dannell was able to successfully contain the Murkmure Stone and had it attached to the top of a staff.",
    "The mimic in the basement of the Varkenbluff History Museum was Dr. Cassee Dannell's pet. She named it Mr. Chompers.",
    "To date, Mr. Chompers has been responsible for the loss of 7 priceless artifacts in the basement of the Varkenbluff History Museum.",
    "Instead of making an unarmed strike, you can instead try to grapple, push, or shove a creature prone.",
    "You will never have perfect information and no plan is without fault. That's the fun part.",
    "A target with Half Cover has +2 to AC and Dexterity saving throws.",
    "A target with 3/4 Cover has +5 to AC and Dexterity saving throws.",
    "If you roll a 20 on an attack roll, you automatically hit and roll all damage dice twice.",
    "When using Two-weapon fighting, only add your damage bonus to the first attack.",
    "You can break up the movement on your turn, performing actions between movements.",
    "You can use Divination magic to absolutely destroy any hopes your DM had of creating mystery and intrigue.",
    "With Conjuration magic, you can take the D&D tradition of making things up to its logical extreme.",
    "Theoretically, Evocation magic can produce a wide variety of effects. Usually, those effects involve trying to roll as many damage dice as possible.",
    "Necromancy magic manipulates life and death energies. You can't cast these spells unless your wardrobe is at least 70% black.",
    "The Golden Vault was founded by a particularly generous Gold Dragon as a means of tricking people into doing its bidding.",
    "No one knows who founded the Golden Vault or when, not even your DM.",
    "Your DM has probably been forgetting about Heroic Inspiration. Try asking for it nicely.",
    "If your spell has an attack, you roll. If your spell has a save, the enemy rolls.",
    "You make a Long Jump of a distance equal to your Strength score by taking a 10ft running start.",
    "You can make encounters easier by being more careful, communicating with your party, taking notes, and bribing the DM.",
    "Just because something is on a map someone drew for you doesn't mean it's actually there.",
    "Just because something isn't on a map that someone drew for you doesn't mean it isn't actually there.",
    "You can open the options menu in D&D by writing a question on a slip of paper and passing it to your DM.",
    "If you are unconscious but stable, you regain 1 hit point after 1d4 hours.",
    "A round of combat roughly translates to 6 seconds of in-game time.",
    "Someone who charms another creature has advantage on any ability check to interact socially with that creature.",
    "Invisible creatures aren't imperceptible. Creatures still make sound and leave footprints while invisible.",
    "Abjuration is the school of protective magic, perfect for kids who claimed to have a force field in schoolyard games.",
    "If you roll a 20 on a death saving throw, you regain 1 hit point (and thus regain consciousness).",
    "If you roll a 1 on a death saving throw, it counts as 2 failures.",
    "Some spells can be cast at higher levels for more powerful effects, and many cantrips will increase in damage as you level up.",
    "A target with total cover can't be targeted directly by an attack or spell, but could still be caught in an AoE.",
    "Combat does not have to be resolved by reducing your enemies' hit points to 0. You could always flee, or convince them that fighting is not the best course of action.",
    "Long Jumps and High Jumps without a 10ft running start are only half as effective.",
    "If you ever aren't sure of something, ask your DM for help or options.",
    "Illusion magic deceives the minds of others, which is totally different from Enchantment and way cooler, Mom.",
    "Attacks against a restrained/grappled creature have advantage, and that creature's attacks have disadvantage.",
    "A poisoned creature has disadvantage on attack rolls and ability checks.",
    "Transmutation magic can be used to alter the properties of objects, or just turn everything into a goat.",
    "Enchantment magic affects the minds of others but in a way that's totally different from Illusion magic, for sure.",
    "A creature that falls from a height takes 1d6 damage for every 10 feet it fell, to a maximum of 20d6.",
    "If you are reduced to 0 hit points, you being making death saving throws each turn, until you reach 3 success or failures.",
    "A creature can hold ita breath for a number of minutes equal to 1 + its Constitution modifier.",
    "Don't be afraid of a retreat if combat isn't going well. Cowardice is typically preferable to death.",
    "You cant hide from a creature that can see you clearly, and making noise will give away your position afterward.",
    "You can use your Reaction to make an Opportunity Attack when a creature that you can see moves out of your reach.",
    "If you don't want enemies to take opportunity attacks against you for a turn, you can take the Disengage action.",
    "You can take the Dodge action to give all attacks against you disadvantage and gain advantage on Dexterity saving throws until your next turn.",
    "Arcana checks relate to your knowledge of magic, eldritch beings, mystic tradition, and other nerd shit.",
    "Sleight of hand checks typically relate to stealing, hiding, or manipulating an object. Surely you wouldn't be planning on doing any of that?",
    "Intimidation checks are what you use when Persuasion and Deception didn't work and you're getting annoyed about it.",
    "Throw out a Deception check if you need to fool someone into believing you. Please do this instead of actually lying to your DM.",
    "An Acrobatics check may be used if you need delicate finesse of motion, or if you really want to show off.",
    "If you take damage while Concentrating on a spell, you must succeed on a Constitution saving throw of DC 10 or half of the damage, whichever is higher.",
    "Performance checks finally give you the chance to turn the game into a musical and dance show.",
    "You can take the Help action to give an ally advantage on an ability check or attack roll, as long as it's something that actually makes sense for you to be able to help with.",
    "Animal Handling checks are used for handling animals. I'm not sure what you wanted me to explain here.",
    "If you increase your Constitution modifier, your hit points change retroactively, as if you'd had the new modifier from level 1.",
    "You can perform an Investigation check if you want your character to be like Benoit Blanc, even if you the player are not.",
    "Passive Perception scores determine if a creature notices something even if they aren't looking for it.",
    "Use a Persuasion check to win people over, make friends, or haggle! The Dealer will not be haggling with you.",
    "In Lightly Obscured areas (e.g. dim light, patchy fog, modest foliage), Perception checks with sight have disadvantage.",
    "Medicine checks can let you stabilize a dying creature or diagnose someone with an illness, such as Ligma.",
    "The Hide action will let you make a Stealth check to disappear from sight, as long as the environment and conditions allow it.",
    "A hidden creature makes their first attack with advantage, and is then revealed.",
    "Religion checks will allow you to recall lore about various gods and faiths, but it won't erase the feeling of sin for your past deeds.",
    "You can use the Dash action to double your speed for the turn.",
    "Nature checks can be used to learn more about the land, the creatures in it, or to try roleplaying as a druid.",
    "You can use a History check to learn more about the lore of an object, person, place, or event, which your DM totally won't have to come up with on the spot.",
    "Suspicious of an NPC's intent? Roll an Insight check and become even more suspicious!",
    "There are no wrong paths in D&D, just paths that your DM hasn't prepared for.",
    "The ongoing effects of a spell cast multiple times do not stack, only the most potent one.",
    "The ongoing effects of different spells combine additively.",
    "Some spells can be cast as rituals, which takes 10 minutes but does not consume a spell slot.",
    "If you take any damage while at 0 hit points, it counts as a Death Saving Throw failure.",
    "Are you absolutely sure that you remember what all of your magic items are?",
    "No you're right, you should totally save that consumable item. What if it's more important in the future?",
    "Athletics checks determine how well you can perform physical activities, like climbing or opening a jar of pickles.",
    "Use Perception checks to see what's going on  and get into an argument about whether it's really Perception or Investigation.",
    "If you think there are only two options in front of you, try choosing a third option.",
    "There is no Golden Vault. You've just been hallucinating this whole adventure.",
    "The Golden Vault was created by your characters from the future who went back in time.",
    "If need to reach a DC 15 check or are trying to hit a creature with 15 AC, rolling a 15 is good enough to succeed. Meets it, beats it.",
    "Succeeding or failing a throw by 5 or even 10 may have additional consequences, for better or for worse.",
    "You can always choose to voluntarily fail an Ability Check or Saving Throw.",
    "Feel free to ask what you might have missed after an adventure. Someone probably spent a bunch of time preparing it.",
    "The real Golden Vault was the friends we made along the way.",
    "Survival checks can be used for finding food, tracking creatures, or auditioning for Survivor.",
    "Bringing a good snack or drink may convince the DM to award you Heroic Inspiration.",
    "If you let your DM know what sort of items your character might want, there is a much higher likelihood of those items becoming available.",
    "Don't be afraid to fail trying to do something cool. Failures are often the most memorable parts of an adventure.",
    "Your DM wants this to be an epic adventure just as much as you do. You won't be harshly punished for trying something awesome or innovative.",
    "The economy of the world of D&D doesn't make sense. Don't think about it too hard.",
    "If you're worried about a particularly scary foe, it could be worth spending your turn making some kind of check to learn about it's abilities, vulnerabilities, resistances, or intents.",
    "If you aren't happy with some aspect of your character, bring it up with your DM. You may be able to change it, or change the way youre interacting with it.",
    "The Golden Vault was wished into existence by a particularly benevolent vigilante with a genie's lamp.",
    "You've found the secret bonus loading screen tip! The whole party gains Heroic Inspiration, and the first player to point this tip out to the DM will receive a reward.",
    "If a spell takes longer than an action to cast, you must spend each turn concentrating on casting it.",
    "Try to plan your turn and study your available spells and actions on other players' turns. Combat will go much more smoothly if everyone knows what they want to do!",
    "Many creatures, both humanoid and monster, can be influenced or bribed. This includes the DM.",
    "If the DM asks you to make a check and you want to use another skill for that check, try convincing them of why you should be able to use that skill.",
    "Different skill checks yield different results. Rolling an Arcana check may tell you something different about an item than rolling a History check.",
    "Have you checked the items in your inventory lately?",
    "Have you checked your class features lately?",
    "Have you checked your species and background features lately?",
    "The mitochondria is the powerhouse of the cell.",
    "Don't forget to bring a towel.",
    "That chest is definitely a mimic. But what if it isn't?...",
    "Crying is a free action.",
    "Remember: The DM wants you to win.",
    "If combat is going poorly, remember that many humanoids don't enjoy killing and may accept your surrender.",
    "If combat is going well, remember that many creatures don't enjoy doing and may be willing to surrender if you give them a chance.",
    "If you find yourself in dire need of healing, consider taking less damage.",
    "Expertise in Persuasion is not a substitute for Dominate Person.",
    "Expertise in Stealth is not a substitute for Greater Invisibility.",
    "Not every NPC is an untrustworthy charlatan out to ruin your life. But THAT one might be...",
    "If you have to ask, it's probably a war crime.",
    "Don't stress yourself being too cautious. You're on an adventure! Do things!",
    "Just because it's a bad idea doesn't mean it wouldn't be really funny to try it anyway.",
    "The air filter below your microwave should be cleaned every 6 months.",
    "The Golden Vault was founded by a celestial who grew tired with the inefficiencies and corruption of governmental law enformance.",
    "What do you really know about the Golden Vault's intentions and plans, anyway?...",
    "NPCs can be wrong about things. It will be much easier to notice when they're wrong if you take notes on what they tell you.",
    "Remembering that you wrote down relevant information in your notes may be cause for your DM to award you Heroic Inspiration.",
    "Heroic Inspiration can be spent to give yourself advantage or an enemy disadvantage on a roll.",
    "You can only have one use of Heroic Inspiration at a time. If you would gain Inspiration while you already have it, you can give it to another party member.",
    "If you aren't enjoying something about the campaign, let the DM know and there may be something that can be done about it.",
    "If you are enjoying something a out the campaign, let the DM know so they know what parts are working well.",
    "The Golden Vault is secretly a front for a powerful devil to exert their influence on the world unhindered.",
    "Dr. Cassee Dannell and Curator Alda Arkin had a passionate relationship while attending university together, but neither would ever admit it.",
    "Are you absolutely sure that Meera Raheer isn't just a particularly eloquent mimic?",
    "Meera Raheer joined the Golden Vault after her law-abiding parents were framed by the mayor for embezzlement.",
    "It can be difficult to want to take an Attack of Opportunity, but never underestimate the tactical value of repositioning. Your enemies sure won't.",
    "By default, casting a spell is not subtle. Verbal components require spoken words, and somatic components require significant arm movement.",
    "You must be proficient with shields or a type of armor in order to cast spells while wearing it.",
    "As written, only a character class that can learn a spell can use a spell scroll to cast that spell. This is a stupid and boring rule that will not be followed.",
];
